openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample Product API
  description: An example API for managing products
servers:
  - url: https://pkcpwhzg9k.execute-api.eu-central-1.amazonaws.com/prod/
schemes:
  - https
paths:
  /product:
    get:
      summary: Get all products
      description: Retrieve a list of all available products.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
    post:
      summary: Create a new product
      description: Add a new product to the inventory.
      requestBody:
        description: Product details to add.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Failed to perform operation

  /product/{productId}:
    get:
      summary: Get a product by ID
      description: Retrieve a specific product by its ID.
      parameters:
        - name: productId
          in: path
          description: ID of the product to retrieve.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Failed to perform operation
    delete:
      summary: Delete a product by ID
      description: Delete a specific product by its ID.
      parameters:
        - name: productId
          in: path
          description: ID of the product to delete.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  body:
                    $ref: "#/components/schemas/Product"
        "500":
          description: Failed to perform operation
    put:
      summary: Update a product by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the product to update
          schema:
            type: string
      requestBody:
        description: Updated product data
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product" # Assuming you have a schema for the product
      responses:
        "200":
          description: Successfully updated product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product" # Assuming you have a schema for the product
        "404":
          description: Product not found
        "500":
          description: Failed to perform operation

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
      required:
        - id
        - name
        - price
